### ISSUE TITLE
Return claims from ValidateRequest

### ISSUE THREAD

**Issue by MOZGIII** [auth0-community/auth0-go#20]
Claims are really useful, why not return them from `ValidateRequest` along with the `token` in `JWTValidator`?

```go
ValidateRequest(r *http.Request) (*jwt.JSONWebToken, *jwt.Claims, error)
```

I understand that's an API change, but it's a good one.

**Comment by charly3pins** [comment]
The `claims` are the content of the JWT so the `ValidateRequest` only needs to validate if the request it's correct and return the corresponding jwt or error.

When you have the `jwt` with a nil error it's the moment you can extract the claims with: 
`func (v *JWTValidator) Claims(r *http.Request, token *jwt.JSONWebToken, values ...interface{}) error`

I think the design of the functionality it's correct in order to separate the responsibilities in different functions.
